CodeSystem:     GofrTaskPermissionCodeSystem
Id:             gofr-task-permission-codesystem
Title:          "Code system for task permissions."
* ^date = "2021-07-27T12:11:04.362Z"
* ^version = "0.0.1"
* #*      "All"     "Can do any task."
* #facility_registry_can_add_facility   "Can add new facility registry facility"
* #facility_registry_can_add_service   "Can add new service"
* #facility_registry_can_add_jurisdiction   "Can add new facility registry jurisdiction"
* #facility_registry_can_add_organization   "Can add new facility registry organization"
* #facility_registry_can_add_terminologies   "Can add facility registry terminologies"
* #facility_registry_can_view_facility   "Can view new facility registry facility"
* #facility_registry_can_view_service   "Can view new service"
* #facility_registry_can_view_jurisdiction   "Can view new facility registry jurisdiction"
* #facility_registry_can_view_organization   "Can view facility registry organizations"
* #facility_registry_can_view_terminologies   "Can view facility registry terminologies"
* #facility_registry_can_view_update_facility_details_requests_report   "Can view facility registry requests to update facility details"
* #facility_registry_can_view_new_facility_requests_report   "Can view facility registry requests to create new facility"
* #facility_registry_can_edit_facility   "Can edit facility registry facility"
* #facility_registry_can_edit_update_facility_details_request   "Can edit facility registry request to update facility details"
* #facility_registry_can_edit_new_facility_request   "Can edit facility registry request to create new facility"
* #facility_registry_can_edit_jurisdiction   "Can edit facility registry jurisdiction"
* #facility_registry_can_edit_organization   "Can edit facility registry organization"
* #facility_registry_can_edit_service   "Can edit facility registry service"
* #facility_registry_can_edit_terminologies   "Can edit facility registry terminologies"
* #facility_registry_can_delete_facility   "Can delete new facility registry facility"
* #facility_registry_can_delete_service   "Can delete new service"
* #facility_registry_can_delete_jurisdiction   "Can delete new facility registry jurisdiction"
* #facility_registry_can_delete_organization   "Can delete facility registry organization"
* #facility_registry_can_delete_terminologies   "Can delete facility registry terminologies"
* #facility_registry_can_delete_new_facility_request   "Can delete facility registry request to create new facility"
* #facility_registry_can_delete_update_facility_details_request   "Can delete facility registry request to update facility details"
* #facility_registry_can_request_new_facility   "Can request addition of new facility"
* #facility_registry_can_request_update_of_facility_details   "Can request update of facility details"
* #facility_registry_can_approve_update_facility_details_requests   "Can approve facility registry requests to update facility details"
* #facility_registry_can_approve_new_facility_request   "Can approve facility registry requests to add new facility"
* #facility_registry_can_reject_update_facility_details_requests   "Can reject facility registry requests to update facility details"
* #facility_registry_can_reject_new_facility_request   "Can reject facility registry requests to add new facility"

ValueSet:       GofrTaskPermissionValueSet
Id:             gofr-task-permission
Title:          "Code system for task permissions."
* ^date = "2021-07-27T12:11:04.362Z"
* ^version = "0.0.1"
* codes from system GofrTaskPermissionCodeSystem